### ISSUE TITLE
Implement Queuing for Server side plan evaluation

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-server-core#286]
We need Implement Queuing for Server side plan evaluation.

This is because plan evaluation may be evaluating a plan that maybe be applicable in all jurisdictions in a country.

It has been decided that we shall rabbitMQ for queuing

We need to add a database table that will track the jobs posted to RabbitMQ. The information in the database table will allow queues to resume in case the queue is cleared for any reason while there were tasks queued up that were not completed

We need to decide the unit of a job to be queued by rabbitMQ
1. Use entity as unit of job
2. Use jurisdiction and action as a unit of job

**1. Use entity as unit**
Using entity will mean we have as many jobs queued as per the entities targeted in the plan e.g all residential structures, all families,  all family members,  and all tasks that are applicable by the plan.

This has the advantages in that in case of restart we shall not process any tasks for entities already completed.

**2.  Use jurisdiction and entity as unit**
This will mean that we have jobs queued for each jurisdiction that is applicable for the plan. We could break down so that we have a job per action and jurisdiction. This will imply that each job will be handling an action in the plan per jurisdiction

This has the advantages in that we can track task generation by jurisdictions. In case jurisdictions have a lot of structures during any restart this would mean restarting evaluation for jobs queued that were partially completed

When all the evaluation is complete and all rabbitMQ  tasks are complete, we need to purge the jobs table

**Comment by ukanga** [comment]
I am not sure if it is necessary to have a tracking table, but it could still prove useful. Normally, RabbitMQ can persist work even across restarts. In the rare occasion where you have to clear the RabbitMQ data folder is when perhaps you may need to re-add the tasks for processing.

I would focus on the task that needs to be defined. Have we settled on how the integration will work? Are we interfacing directly with RabbitMQ, or is this issue to track and determine the scheduler to implement to provide this functionality?

**Comment by githengi** [comment]
The integration will work when during plan evaluation tasks will be created in rabbitMQ.

**Comment by githengi** [comment]
We have chosen to not support the tracking table for now. @rehammuzzamil

**Comment by rehammuzzamil** [comment]
As per our discussion, we have decided to keep **RabbitMQ** code at the server core, and do not include any dependency of RabbitMQ in the plan-evaluator library, as it is used by both server and Android client.
For the MVP level, we have decided to keep the unit of Job at the Jurisdiction level. For the fine-grained details, we are going to modify **evaluatePlan(PlanDefinition planDefinition, TriggerType triggerEvent, List<Jurisdiction> jurisdictions)** method and inside for loop, we are going to replace evaluatePlan call to the queue in RabbitMQ, for which we will expose an interface which will act as a callback on PlanEvaluator.java such as QueuingHelper and provide its implementation on the server-core. We have decided to avoid serialization, therefore we will pass planId, TriggerType, and locationId to the queue instead of the Objects. On the server core, where we will be receiving Job we would construct PlanDefinition and Jurisdiction Object from planId and locationId respectively. We would need to optimize method calls to get PlanDefinition object from the identifier, for that we would include **Caching** annotations on the PlanService methods which return or modify plans. The model of RabbitMQ queue would be **FIFO** and all the configuration related details will be defined in the configs module (Opensrp.properties) @githengi

**Comment by githengi** [comment]
@rehammuzzamil this sounds good please proceed with the implementation

**Comment by githengi** [comment]
@rehammuzzamil 
We have decided to extend queuing so that tasks are granular at the entity being evaluated

When a plan is being evaluated a task will be created for each jurisdiction
When this task runs it will get the target resources and will create a task for each resource
The second kind of tasks will now evaluate an action and the resource
